name: go_router_learn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.1.4
  responsive_framework: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.10
  build_verify: ^3.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0

flutter:
  uses-material-design: true
